export interface Topic {
  id: string;
  title: string;
  description: string;
  category: 'grammar' | 'vocabulary' | 'conversation';
}

export interface LevelCurriculum {
  level: string;
  name: string;
  description: string;
  topics: Topic[];
}

export const CEFR_CURRICULUM: LevelCurriculum[] = [
  {
    level: 'A1',
    name: 'Beginner',
    description: 'Can understand and use familiar everyday expressions and very basic phrases.',
    topics: [
      { id: 'a1_1', title: 'Alphabet & Phonics', description: 'Mastering English sounds', category: 'vocabulary' },
      { id: 'a1_2', title: 'Numbers 1-20', description: 'Basic counting', category: 'vocabulary' },
      { id: 'a1_3', title: 'Greetings & Farewells', description: 'Saying hello and goodbye', category: 'conversation' },
      { id: 'a1_4', title: 'Personal Pronouns', description: 'I, you, he, she, it...', category: 'grammar' },
      { id: 'a1_5', title: 'Verb "To Be" (Present)', description: 'Am, is, are', category: 'grammar' },
      { id: 'a1_6', title: 'Introducing Yourself', description: 'Name, age, and country', category: 'conversation' },
      { id: 'a1_7', title: 'Colors', description: 'Basic color names', category: 'vocabulary' },
      { id: 'a1_8', title: 'Common Objects', description: 'Classroom and home items', category: 'vocabulary' },
      { id: 'a1_9', title: 'Family Members', description: 'Talking about relatives', category: 'vocabulary' },
      { id: 'a1_10', title: 'Possessive Adjectives', description: 'My, your, his, her...', category: 'grammar' },
      { id: 'a1_11', title: 'Plural Nouns', description: 'Regular plurals (-s, -es)', category: 'grammar' },
      { id: 'a1_12', title: 'Demonstratives', description: 'This, That, These, Those', category: 'grammar' },
      { id: 'a1_13', title: 'Numbers 21-100', description: 'Higher numbers', category: 'vocabulary' },
      { id: 'a1_14', title: 'Telling the Time', description: 'Basic time expressions', category: 'vocabulary' },
      { id: 'a1_15', title: 'Days of the Week', description: 'Monday to Sunday', category: 'vocabulary' },
      { id: 'a1_16', title: 'Months & Seasons', description: 'Yearly cycles', category: 'vocabulary' },
      { id: 'a1_17', title: 'Prepositions of Place', description: 'In, On, Under', category: 'grammar' },
      { id: 'a1_18', title: 'Present Simple: Affirmative', description: 'I work, he works', category: 'grammar' },
      { id: 'a1_19', title: 'Present Simple: Negative', description: 'I don\'t work, he doesn\'t', category: 'grammar' },
      { id: 'a1_20', title: 'Present Simple: Questions', description: 'Do you work?', category: 'grammar' },
      { id: 'a1_21', title: 'Adverbs of Frequency', description: 'Always, Never, Often', category: 'grammar' },
      { id: 'a1_22', title: 'Daily Routine', description: 'Talking about your day', category: 'conversation' },
      { id: 'a1_23', title: 'Likes & Dislikes', description: 'Food and hobbies', category: 'conversation' },
      { id: 'a1_24', title: 'Can/Can\'t (Ability)', description: 'What you can do', category: 'grammar' },
      { id: 'a1_25', title: 'Parts of the Body', description: 'Head, shoulders, knees...', category: 'vocabulary' },
      { id: 'a1_26', title: 'Describing People (Look)', description: 'Tall, short, hair color', category: 'vocabulary' },
      { id: 'a1_27', title: 'Describing People (Traits)', description: 'Nice, funny, smart', category: 'vocabulary' },
      { id: 'a1_28', title: 'Clothes & Fashion', description: 'What are you wearing?', category: 'vocabulary' },
      { id: 'a1_29', title: 'My House', description: 'Rooms and furniture', category: 'vocabulary' },
      { id: 'a1_30', title: 'There is / There are', description: 'Describing existence', category: 'grammar' },
      { id: 'a1_31', title: 'Prepositions of Time', description: 'At, In, On', category: 'grammar' },
      { id: 'a1_32', title: 'Weather', description: 'Sunny, rainy, cloudy', category: 'vocabulary' },
      { id: 'a1_33', title: 'Question Words', description: 'Who, What, Where, Why', category: 'grammar' },
      { id: 'a1_34', title: 'Imperatives', description: 'Giving instructions', category: 'grammar' },
      { id: 'a1_35', title: 'Object Pronouns', description: 'Me, you, him, her...', category: 'grammar' },
      { id: 'a1_36', title: 'Present Continuous: Intro', description: 'I am working', category: 'grammar' },
      { id: 'a1_37', title: 'Present Continuous: Q&A', description: 'Are you working?', category: 'grammar' },
      { id: 'a1_38', title: 'Simple vs Continuous', description: 'When to use which', category: 'grammar' },
      { id: 'a1_39', title: 'Transport', description: 'Car, bus, train, plane', category: 'vocabulary' },
      { id: 'a1_40', title: 'Places in Town', description: 'Bank, park, school', category: 'vocabulary' },
      { id: 'a1_41', title: 'Giving Directions', description: 'Left, right, straight', category: 'conversation' },
      { id: 'a1_42', title: 'Countable/Uncountable', description: 'Basic food items', category: 'grammar' },
      { id: 'a1_43', title: 'Some / Any', description: 'Quantifiers', category: 'grammar' },
      { id: 'a1_44', title: 'How much / How many', description: 'Asking about quantity', category: 'grammar' },
      { id: 'a1_45', title: 'Free Time Activities', description: 'Reading, swimming, etc.', category: 'vocabulary' },
      { id: 'a1_46', title: 'Sports', description: 'Football, tennis, etc.', category: 'vocabulary' },
      { id: 'a1_47', title: 'Animals', description: 'Pets and farm animals', category: 'vocabulary' },
      { id: 'a1_48', title: 'Feelings', description: 'Happy, sad, angry', category: 'vocabulary' },
      { id: 'a1_49', title: 'Basic Conversations', description: 'Putting it all together', category: 'conversation' },
      { id: 'a1_50', title: 'A1 Final Review', description: 'Consolidating A1 knowledge', category: 'conversation' },
    ]
  },
  {
    level: 'A2',
    name: 'Elementary',
    description: 'Can understand sentences and frequently used expressions related to areas of most immediate relevance.',
    topics: [
      { id: 'a2_1', title: 'Past Simple: To Be', description: 'Was and Were', category: 'grammar' },
      { id: 'a2_2', title: 'Past Simple: Regular', description: 'Worked, played, lived', category: 'grammar' },
      { id: 'a2_3', title: 'Past Simple: Irregular', description: 'Went, saw, had', category: 'grammar' },
      { id: 'a2_4', title: 'Past Simple: Q&A', description: 'Did you work?', category: 'grammar' },
      { id: 'a2_5', title: 'Used to', description: 'Past habits', category: 'grammar' },
      { id: 'a2_6', title: 'Past Continuous', description: 'I was working', category: 'grammar' },
      { id: 'a2_7', title: 'Simple vs Continuous Past', description: 'Interrupted actions', category: 'grammar' },
      { id: 'a2_8', title: 'Comparatives', description: 'Better, faster, stronger', category: 'grammar' },
      { id: 'a2_9', title: 'Superlatives', description: 'The best, the fastest', category: 'grammar' },
      { id: 'a2_10', title: 'As...as', description: 'Equality in comparison', category: 'grammar' },
      { id: 'a2_11', title: 'Future: Going to', description: 'Plans and intentions', category: 'grammar' },
      { id: 'a2_12', title: 'Future: Will', description: 'Predictions and promises', category: 'grammar' },
      { id: 'a2_13', title: 'Present Perfect: Intro', description: 'I have seen', category: 'grammar' },
      { id: 'a2_14', title: 'Just, Already, Yet', description: 'Present perfect markers', category: 'grammar' },
      { id: 'a2_15', title: 'Perfect vs Simple Past', description: 'Experience vs specific time', category: 'grammar' },
      { id: 'a2_16', title: 'Modals: Have to', description: 'Obligation', category: 'grammar' },
      { id: 'a2_17', title: 'Modals: Should', description: 'Giving advice', category: 'grammar' },
      { id: 'a2_18', title: 'Modals: Must', description: 'Strong obligation', category: 'grammar' },
      { id: 'a2_19', title: 'Relative Clauses', description: 'Who, Which, That', category: 'grammar' },
      { id: 'a2_20', title: 'Adverbs of Manner', description: 'Quickly, slowly, well', category: 'grammar' },
      { id: 'a2_21', title: 'Too / Enough', description: 'Quantity and degree', category: 'grammar' },
      { id: 'a2_22', title: 'Infinitives vs -ing', description: 'Basic patterns', category: 'grammar' },
      { id: 'a2_23', title: 'Zero Conditional', description: 'General truths', category: 'grammar' },
      { id: 'a2_24', title: 'First Conditional', description: 'Real possibilities', category: 'grammar' },
      { id: 'a2_25', title: 'Phrasal Verbs Intro', description: 'Get up, sit down, etc.', category: 'vocabulary' },
      { id: 'a2_26', title: 'Health & Body', description: 'Advanced body parts', category: 'vocabulary' },
      { id: 'a2_27', title: 'At the Doctor\'s', description: 'Describing symptoms', category: 'conversation' },
      { id: 'a2_28', title: 'Shopping', description: 'Prices and sizes', category: 'vocabulary' },
      { id: 'a2_29', title: 'Restaurant', description: 'Ordering food', category: 'conversation' },
      { id: 'a2_30', title: 'At the Airport', description: 'Check-in and security', category: 'conversation' },
      { id: 'a2_31', title: 'Booking a Hotel', description: 'Reservations', category: 'conversation' },
      { id: 'a2_32', title: 'Jobs & Workplace', description: 'Professional titles', category: 'vocabulary' },
      { id: 'a2_33', title: 'Technology', description: 'Gadgets and internet', category: 'vocabulary' },
      { id: 'a2_34', title: 'Environment', description: 'Nature and pollution', category: 'vocabulary' },
      { id: 'a2_35', title: 'Entertainment', description: 'Movies and books', category: 'vocabulary' },
      { id: 'a2_36', title: 'Music', description: 'Genres and instruments', category: 'vocabulary' },
      { id: 'a2_37', title: 'Hobbies', description: 'Advanced interests', category: 'vocabulary' },
      { id: 'a2_38', title: 'Describing Places', description: 'City vs Country', category: 'vocabulary' },
      { id: 'a2_39', title: 'Education', description: 'School subjects', category: 'vocabulary' },
      { id: 'a2_40', title: 'Life Events', description: 'Birth, marriage, etc.', category: 'vocabulary' },
      { id: 'a2_41', title: 'Appearance', description: 'Advanced descriptions', category: 'vocabulary' },
      { id: 'a2_42', title: 'Character Traits', description: 'Personality adjectives', category: 'vocabulary' },
      { id: 'a2_43', title: 'Food & Cooking', description: 'Recipes and methods', category: 'vocabulary' },
      { id: 'a2_44', title: 'Quantities', description: 'A bottle of, a box of...', category: 'vocabulary' },
      { id: 'a2_45', title: 'Suggestions', description: 'Why don\'t we...?', category: 'conversation' },
      { id: 'a2_46', title: 'Permission', description: 'Can I...? May I...?', category: 'conversation' },
      { id: 'a2_47', title: 'Invitations', description: 'Inviting and responding', category: 'conversation' },
      { id: 'a2_48', title: 'Complaining', description: 'Polite complaints', category: 'conversation' },
      { id: 'a2_49', title: 'A2 Grammar Review', description: 'Consolidating A2 grammar', category: 'grammar' },
      { id: 'a2_50', title: 'A2 Final Assessment', description: 'Elementary level completion', category: 'conversation' },
    ]
  },
  {
    level: 'B1',
    name: 'Intermediate',
    description: 'Can understand the main points of clear standard input on familiar matters regularly encountered.',
    topics: [
      { id: 'b1_1', title: 'Present Perfect Continuous', description: 'I have been working', category: 'grammar' },
      { id: 'b1_2', title: 'Simple vs Continuous Perfect', description: 'State vs Action', category: 'grammar' },
      { id: 'b1_3', title: 'Past Perfect Simple', description: 'I had worked', category: 'grammar' },
      { id: 'b1_4', title: 'Past Perfect Continuous', description: 'I had been working', category: 'grammar' },
      { id: 'b1_5', title: 'Future Continuous', description: 'I will be working', category: 'grammar' },
      { id: 'b1_6', title: 'Future Perfect', description: 'I will have worked', category: 'grammar' },
      { id: 'b1_7', title: 'Passive Voice: Intro', description: 'It is done', category: 'grammar' },
      { id: 'b1_8', title: 'Passive Voice: Advanced', description: 'Future and modals', category: 'grammar' },
      { id: 'b1_9', title: 'Second Conditional', description: 'Hypothetical present', category: 'grammar' },
      { id: 'b1_10', title: 'Third Conditional', description: 'Hypothetical past', category: 'grammar' },
      { id: 'b1_11', title: 'Wish / If only', description: 'Regrets and desires', category: 'grammar' },
      { id: 'b1_12', title: 'Reported Speech: Statements', description: 'He said that...', category: 'grammar' },
      { id: 'b1_13', title: 'Reported Speech: Q&A', description: 'He asked if...', category: 'grammar' },
      { id: 'b1_14', title: 'Modals of Deduction', description: 'Must, Might, Can\'t', category: 'grammar' },
      { id: 'b1_15', title: 'Relative Clauses', description: 'Defining vs Non-defining', category: 'grammar' },
      { id: 'b1_16', title: 'Gerunds & Infinitives', description: 'Advanced patterns', category: 'grammar' },
      { id: 'b1_17', title: 'Participle Adjectives', description: '-ed vs -ing', category: 'grammar' },
      { id: 'b1_18', title: 'Question Tags', description: '...don\'t you?', category: 'grammar' },
      { id: 'b1_19', title: 'Indirect Questions', description: 'Could you tell me...?', category: 'grammar' },
      { id: 'b1_20', title: 'Causative', description: 'Have something done', category: 'grammar' },
      { id: 'b1_21', title: 'Contrast Connectors', description: 'However, Although', category: 'grammar' },
      { id: 'b1_22', title: 'Reason & Result', description: 'Because, So, Therefore', category: 'grammar' },
      { id: 'b1_23', title: 'Relationships', description: 'Phrasal verbs for dating', category: 'vocabulary' },
      { id: 'b1_24', title: 'Work & Business', description: 'Professional phrasal verbs', category: 'vocabulary' },
      { id: 'b1_25', title: 'Travel Phrasal Verbs', description: 'Check in, set off, etc.', category: 'vocabulary' },
      { id: 'b1_26', title: 'Common Idioms', description: 'Everyday expressions', category: 'vocabulary' },
      { id: 'b1_27', title: 'Business Meetings', description: 'Conducting a meeting', category: 'conversation' },
      { id: 'b1_28', title: 'Business Emails', description: 'Formal writing', category: 'conversation' },
      { id: 'b1_29', title: 'Presentations', description: 'Structure and delivery', category: 'conversation' },
      { id: 'b1_30', title: 'Crime & Punishment', description: 'Legal vocabulary', category: 'vocabulary' },
      { id: 'b1_31', title: 'Media & News', description: 'Journalism vocabulary', category: 'vocabulary' },
      { id: 'b1_32', title: 'Science & Innovation', description: 'Modern discoveries', category: 'vocabulary' },
      { id: 'b1_33', title: 'Global Issues', description: 'Poverty, climate, etc.', category: 'vocabulary' },
      { id: 'b1_34', title: 'Psychology', description: 'Behavior and mind', category: 'vocabulary' },
      { id: 'b1_35', title: 'Art & Creativity', description: 'Painting, music, etc.', category: 'vocabulary' },
      { id: 'b1_36', title: 'History & Heritage', description: 'Talking about the past', category: 'vocabulary' },
      { id: 'b1_37', title: 'Money & Finance', description: 'Banking and economy', category: 'vocabulary' },
      { id: 'b1_38', title: 'Advertising', description: 'Marketing strategies', category: 'vocabulary' },
      { id: 'b1_39', title: 'Success & Failure', description: 'Achievement vocabulary', category: 'vocabulary' },
      { id: 'b1_40', title: 'Luck & Coincidence', description: 'Chance events', category: 'vocabulary' },
      { id: 'b1_41', title: 'Memory & Learning', description: 'Cognitive vocabulary', category: 'vocabulary' },
      { id: 'b1_42', title: 'Dating & Romance', description: 'Modern relationships', category: 'vocabulary' },
      { id: 'b1_43', title: 'Conflict Resolution', description: 'Solving problems', category: 'conversation' },
      { id: 'b1_44', title: 'Cultural Differences', description: 'Global awareness', category: 'conversation' },
      { id: 'b1_45', title: 'Urban Living', description: 'City life challenges', category: 'vocabulary' },
      { id: 'b1_46', title: 'Rural Life', description: 'Country life pros/cons', category: 'vocabulary' },
      { id: 'b1_47', title: 'Extreme Sports', description: 'Adrenaline activities', category: 'vocabulary' },
      { id: 'b1_48', title: 'Fashion & Identity', description: 'Self-expression', category: 'vocabulary' },
      { id: 'b1_49', title: 'B1 Skills Review', description: 'Intermediate consolidation', category: 'conversation' },
      { id: 'b1_50', title: 'B1 Final Assessment', description: 'Intermediate level completion', category: 'conversation' },
    ]
  },
  {
    level: 'B2',
    name: 'Upper Intermediate',
    description: 'Can understand the main ideas of complex text on both concrete and abstract topics.',
    topics: [
      { id: 'b2_1', title: 'Narrative Tenses', description: 'Review and practice', category: 'grammar' },
      { id: 'b2_2', title: 'Future in the Past', description: 'I was going to...', category: 'grammar' },
      { id: 'b2_3', title: 'Advanced Passive', description: 'It is said that...', category: 'grammar' },
      { id: 'b2_4', title: 'Mixed Conditionals', description: 'Complex time relationships', category: 'grammar' },
      { id: 'b2_5', title: 'Inversion Intro', description: 'Never have I...', category: 'grammar' },
      { id: 'b2_6', title: 'Cleft Sentences', description: 'It is... that...', category: 'grammar' },
      { id: 'b2_7', title: 'Nominal Clauses', description: 'What I need is...', category: 'grammar' },
      { id: 'b2_8', title: 'Advanced Modals', description: 'Should have, Could have', category: 'grammar' },
      { id: 'b2_9', title: 'Subjunctive Mood', description: 'I suggest that...', category: 'grammar' },
      { id: 'b2_10', title: 'Complex Gerunds', description: 'Advanced patterns', category: 'grammar' },
      { id: 'b2_11', title: 'Participle Clauses', description: 'Shortening sentences', category: 'grammar' },
      { id: 'b2_12', title: 'Advanced Relative', description: 'Preposition + which', category: 'grammar' },
      { id: 'b2_13', title: 'Discourse Markers', description: 'Formal vs Informal', category: 'grammar' },
      { id: 'b2_14', title: 'Vague Language', description: 'Hedging and softening', category: 'grammar' },
      { id: 'b2_15', title: 'Emphasizing', description: 'Do/Did for emphasis', category: 'grammar' },
      { id: 'b2_16', title: 'Ellipsis', description: 'Omitting words', category: 'grammar' },
      { id: 'b2_17', title: 'Compound Adjectives', description: 'Well-known, etc.', category: 'grammar' },
      { id: 'b2_18', title: 'Advanced Affixes', description: 'Prefixes and suffixes', category: 'grammar' },
      { id: 'b2_19', title: 'Make vs Do', description: 'Advanced collocations', category: 'vocabulary' },
      { id: 'b2_20', title: 'Take, Get, Have', description: 'Core verb collocations', category: 'vocabulary' },
      { id: 'b2_21', title: 'Phrasal Verbs: Separation', description: 'Transitive patterns', category: 'vocabulary' },
      { id: 'b2_22', title: 'Three-part Phrasal Verbs', description: 'Look forward to, etc.', category: 'vocabulary' },
      { id: 'b2_23', title: 'Work Idioms', description: 'Professional expressions', category: 'vocabulary' },
      { id: 'b2_24', title: 'Emotion Idioms', description: 'Expressing feelings', category: 'vocabulary' },
      { id: 'b2_25', title: 'Money Idioms', description: 'Financial expressions', category: 'vocabulary' },
      { id: 'b2_26', title: 'Academic Writing', description: 'Structure and flow', category: 'conversation' },
      { id: 'b2_27', title: 'Formal Tone', description: 'Citations and style', category: 'conversation' },
      { id: 'b2_28', title: 'Critical Thinking', description: 'Analysis skills', category: 'conversation' },
      { id: 'b2_29', title: 'Debating', description: 'Counter-arguments', category: 'conversation' },
      { id: 'b2_30', title: 'Rhetorical Devices', description: 'Public speaking', category: 'conversation' },
      { id: 'b2_31', title: 'Politics', description: 'Government systems', category: 'vocabulary' },
      { id: 'b2_32', title: 'Law & Justice', description: 'Legal systems', category: 'vocabulary' },
      { id: 'b2_33', title: 'Philosophy', description: 'Ethical theories', category: 'vocabulary' },
      { id: 'b2_34', title: 'Mental Health', description: 'Psychology trends', category: 'vocabulary' },
      { id: 'b2_35', title: 'Sociology', description: 'Social trends', category: 'vocabulary' },
      { id: 'b2_36', title: 'Global Markets', description: 'Economics', category: 'vocabulary' },
      { id: 'b2_37', title: 'Sustainability', description: 'Environment', category: 'vocabulary' },
      { id: 'b2_38', title: 'AI & Ethics', description: 'Technology', category: 'vocabulary' },
      { id: 'b2_39', title: 'Space Exploration', description: 'Modern science', category: 'vocabulary' },
      { id: 'b2_40', title: 'Bioethics', description: 'Genetics', category: 'vocabulary' },
      { id: 'b2_41', title: 'Globalization', description: 'Identity', category: 'vocabulary' },
      { id: 'b2_42', title: 'Migration', description: 'Diversity', category: 'vocabulary' },
      { id: 'b2_43', title: 'Minimalism', description: 'Consumerism', category: 'vocabulary' },
      { id: 'b2_44', title: 'Work-Life Balance', description: 'Modern life', category: 'vocabulary' },
      { id: 'b2_45', title: 'Leadership', description: 'Management', category: 'vocabulary' },
      { id: 'b2_46', title: 'Negotiation', description: 'Professional skills', category: 'conversation' },
      { id: 'b2_47', title: 'Intercultural Skills', description: 'Communication', category: 'conversation' },
      { id: 'b2_48', title: 'Creative Writing', description: 'Narrative voice', category: 'conversation' },
      { id: 'b2_49', title: 'B2 Mastery Review', description: 'Upper Intermediate consolidation', category: 'conversation' },
      { id: 'b2_50', title: 'B2 Final Assessment', description: 'Upper Intermediate completion', category: 'conversation' },
    ]
  },
  {
    level: 'C1',
    name: 'Advanced',
    description: 'Can understand a wide range of demanding, longer texts, and recognise implicit meaning.',
    topics: [
      { id: 'c1_1', title: 'Advanced Inversion', description: 'Complex patterns', category: 'grammar' },
      { id: 'c1_2', title: 'Negative Inversion', description: 'Rarely, Seldom, etc.', category: 'grammar' },
      { id: 'c1_3', title: 'Conditionals: Were it not', description: 'Advanced structures', category: 'grammar' },
      { id: 'c1_4', title: 'Advanced Subjunctive', description: 'Formal usage', category: 'grammar' },
      { id: 'c1_5', title: 'Advanced Future', description: 'Be about to, etc.', category: 'grammar' },
      { id: 'c1_6', title: 'Modal Nuances', description: 'Subtle differences', category: 'grammar' },
      { id: 'c1_7', title: 'Impersonal Passive', description: 'It is believed...', category: 'grammar' },
      { id: 'c1_8', title: 'Perfect Gerunds', description: 'Advanced patterns', category: 'grammar' },
      { id: 'c1_9', title: 'Advanced Clefts', description: 'Emphasis patterns', category: 'grammar' },
      { id: 'c1_10', title: 'Fronting', description: 'Stylistic emphasis', category: 'grammar' },
      { id: 'c1_11', title: 'Nominalization', description: 'Formal writing', category: 'grammar' },
      { id: 'c1_12', title: 'Cohesion', description: 'Advanced flow', category: 'grammar' },
      { id: 'c1_13', title: 'Register & Style', description: 'Formal vs Academic', category: 'grammar' },
      { id: 'c1_14', title: 'Synonyms & Nuance', description: 'Subtle differences', category: 'vocabulary' },
      { id: 'c1_15', title: 'Connotation', description: 'Implicit meaning', category: 'vocabulary' },
      { id: 'c1_16', title: 'Business Metaphor', description: 'Professional imagery', category: 'vocabulary' },
      { id: 'c1_17', title: 'Irony & Sarcasm', description: 'Advanced social', category: 'conversation' },
      { id: 'c1_18', title: 'Euphemisms', description: 'Political correctness', category: 'vocabulary' },
      { id: 'c1_19', title: 'Literary Idioms', description: 'Archaic expressions', category: 'vocabulary' },
      { id: 'c1_20', title: 'Abstract Phrasal Verbs', description: 'Complex meanings', category: 'vocabulary' },
      { id: 'c1_21', title: 'Academic Collocations', description: 'Professional pairs', category: 'vocabulary' },
      { id: 'c1_22', title: 'Prepositional Phrases', description: 'Complex structures', category: 'grammar' },
      { id: 'c1_23', title: 'Adverbial Clauses', description: 'Advanced patterns', category: 'grammar' },
      { id: 'c1_24', title: 'Concessive Clauses', description: 'Advanced contrast', category: 'grammar' },
      { id: 'c1_25', title: 'Rhetorical Punctuation', description: 'Stylistic effect', category: 'grammar' },
      { id: 'c1_26', title: 'Analyzing Prose', description: 'Literary analysis', category: 'conversation' },
      { id: 'c1_27', title: 'Analyzing Poetry', description: 'Literary analysis', category: 'conversation' },
      { id: 'c1_28', title: 'Media Bias', description: 'Propaganda analysis', category: 'conversation' },
      { id: 'c1_29', title: 'Scientific Discourse', description: 'Technical talk', category: 'vocabulary' },
      { id: 'c1_30', title: 'Legal Language', description: 'Basic concepts', category: 'vocabulary' },
      { id: 'c1_31', title: 'Financial Reports', description: 'Economic analysis', category: 'vocabulary' },
      { id: 'c1_32', title: 'Philosophical Inquiry', description: 'Abstract thought', category: 'vocabulary' },
      { id: 'c1_33', title: 'Ethical Dilemmas', description: 'Modern world', category: 'vocabulary' },
      { id: 'c1_34', title: 'Cultural Anthropology', description: 'Social science', category: 'vocabulary' },
      { id: 'c1_35', title: 'Linguistic Diversity', description: 'Language death', category: 'vocabulary' },
      { id: 'c1_36', title: 'Evolution of English', description: 'History', category: 'vocabulary' },
      { id: 'c1_37', title: 'Post-colonial Lit', description: 'Global voices', category: 'vocabulary' },
      { id: 'c1_38', title: 'Modernism', description: 'Art movements', category: 'vocabulary' },
      { id: 'c1_39', title: 'Existentialism', description: 'Philosophy', category: 'vocabulary' },
      { id: 'c1_40', title: 'Advanced Negotiation', description: 'Conflict resolution', category: 'conversation' },
      { id: 'c1_41', title: 'Crisis Communication', description: 'Management', category: 'conversation' },
      { id: 'c1_42', title: 'Strategic Vision', description: 'Planning', category: 'conversation' },
      { id: 'c1_43', title: 'Corporate Responsibility', description: 'Ethics', category: 'vocabulary' },
      { id: 'c1_44', title: 'Future of Work', description: 'Automation', category: 'vocabulary' },
      { id: 'c1_45', title: 'Megacities', description: 'Urban planning', category: 'vocabulary' },
      { id: 'c1_46', title: 'Biodiversity', description: 'Conservation', category: 'vocabulary' },
      { id: 'c1_47', title: 'Quantum Physics', description: 'Conceptual', category: 'vocabulary' },
      { id: 'c1_48', title: 'Neuroscience', description: 'Consciousness', category: 'vocabulary' },
      { id: 'c1_49', title: 'Advanced Proficiency', description: 'C1 consolidation', category: 'conversation' },
      { id: 'c1_50', title: 'C1 Final Assessment', description: 'Advanced completion', category: 'conversation' },
    ]
  },
  {
    level: 'C2',
    name: 'Proficiency',
    description: 'Can understand with ease virtually everything heard or read.',
    topics: [
      { id: 'c2_1', title: 'Mastering Nuance', description: 'Tense usage', category: 'grammar' },
      { id: 'c2_2', title: 'Attitudinal Verbs', description: 'Subtle modality', category: 'grammar' },
      { id: 'c2_3', title: 'Advanced Syntax', description: 'Sentence variety', category: 'grammar' },
      { id: 'c2_4', title: 'Stylistic Inversion', description: 'Fronting', category: 'grammar' },
      { id: 'c2_5', title: 'Archaic Grammar', description: 'Obsolete patterns', category: 'grammar' },
      { id: 'c2_6', title: 'Sociolects', description: 'Dialects of English', category: 'vocabulary' },
      { id: 'c2_7', title: 'Mastering Puns', description: 'Wordplay', category: 'conversation' },
      { id: 'c2_8', title: 'Rhetorical Mastery', description: 'Alliteration, etc.', category: 'conversation' },
      { id: 'c2_9', title: 'Persuasion', description: 'Rhetorical skills', category: 'conversation' },
      { id: 'c2_10', title: 'Evocation', description: 'Rhetorical skills', category: 'conversation' },
      { id: 'c2_11', title: 'Ambiguity', description: 'Advanced semantics', category: 'vocabulary' },
      { id: 'c2_12', title: 'Pragmatics', description: 'Context and meaning', category: 'vocabulary' },
      { id: 'c2_13', title: 'Ideology', description: 'Discourse analysis', category: 'vocabulary' },
      { id: 'c2_14', title: 'Intertextuality', description: 'Literary links', category: 'vocabulary' },
      { id: 'c2_15', title: 'Deconstruction', description: 'Textual analysis', category: 'vocabulary' },
      { id: 'c2_16', title: 'Technical Jargon', description: 'Various fields', category: 'vocabulary' },
      { id: 'c2_17', title: 'Etymology', description: 'History of words', category: 'vocabulary' },
      { id: 'c2_18', title: 'Neologisms', description: 'Slang evolution', category: 'vocabulary' },
      { id: 'c2_19', title: 'Regional Idioms', description: 'Global variations', category: 'vocabulary' },
      { id: 'c2_20', title: 'Obscure Phrasal Verbs', description: 'Rare patterns', category: 'vocabulary' },
      { id: 'c2_21', title: 'Highly Specific Collocations', description: 'Niche pairs', category: 'vocabulary' },
      { id: 'c2_22', title: 'Translation Skills', description: 'Advanced practice', category: 'conversation' },
      { id: 'c2_23', title: 'Interpreting Intro', description: 'Simultaneous skills', category: 'conversation' },
      { id: 'c2_24', title: 'Research Methodologies', description: 'Academic skills', category: 'conversation' },
      { id: 'c2_25', title: 'Writing for Publication', description: 'Professional', category: 'conversation' },
      { id: 'c2_26', title: 'Editing Mastery', description: 'Proofreading', category: 'conversation' },
      { id: 'c2_27', title: 'Philosophical Texts', description: 'Analysis', category: 'conversation' },
      { id: 'c2_28', title: 'Mathematical Concepts', description: 'Abstract talk', category: 'vocabulary' },
      { id: 'c2_29', title: 'Genetic Engineering', description: 'Bioethics', category: 'vocabulary' },
      { id: 'c2_30', title: 'Global Strategy', description: 'Geopolitics', category: 'vocabulary' },
      { id: 'c2_31', title: 'Fiscal Policy', description: 'Macroeconomics', category: 'vocabulary' },
      { id: 'c2_32', title: 'Theoretical Physics', description: 'Advanced', category: 'vocabulary' },
      { id: 'c2_33', title: 'Cognitive Science', description: 'AI', category: 'vocabulary' },
      { id: 'c2_34', title: 'Environmental Policy', description: 'Law', category: 'vocabulary' },
      { id: 'c2_35', title: 'International Law', description: 'Human rights', category: 'vocabulary' },
      { id: 'c2_36', title: 'Western Philosophy', description: 'History', category: 'vocabulary' },
      { id: 'c2_37', title: 'Eastern Traditions', description: 'Philosophy', category: 'vocabulary' },
      { id: 'c2_38', title: 'Comparative Religion', description: 'History', category: 'vocabulary' },
      { id: 'c2_39', title: 'Renaissance to Modern', description: 'Art history', category: 'vocabulary' },
      { id: 'c2_40', title: 'Music Theory', description: 'Criticism', category: 'vocabulary' },
      { id: 'c2_41', title: 'Cinema Studies', description: 'Theory', category: 'vocabulary' },
      { id: 'c2_42', title: 'Architecture', description: 'Urban design', category: 'vocabulary' },
      { id: 'c2_43', title: 'Psychoanalysis', description: 'Psychology', category: 'vocabulary' },
      { id: 'c2_44', title: 'Post-structuralism', description: 'Sociology', category: 'vocabulary' },
      { id: 'c2_45', title: 'Transhumanism', description: 'Future of humanity', category: 'vocabulary' },
      { id: 'c2_46', title: 'Space Colonization', description: 'Ethics', category: 'vocabulary' },
      { id: 'c2_47', title: 'Keynote Addresses', description: 'Public speaking', category: 'conversation' },
      { id: 'c2_48', title: 'World Championship Debate', description: 'Mastery', category: 'conversation' },
      { id: 'c2_49', title: 'Near-Native Mastery', description: 'C2 consolidation', category: 'conversation' },
      { id: 'c2_50', title: 'C2 Final Assessment', description: 'Proficiency completion', category: 'conversation' },
    ]
  }
];
